apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-system
  template:
    metadata:
      labels:
        app: healthcare-system
    spec:
      containers:
      - name: healthcare-system
        image: your-dockerhub-username/healthcare-system:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "newproject.settings"
        volumeMounts:
        - name: media-volume
          mountPath: /app/newproject/media
      volumes:
      - name: media-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-system-service
spec:
  selector:
    app: healthcare-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
