# Generated by Django 3.2.5 on 2021-07-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulancemodel',
            old_name='contactnumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='ambulancemodel',
            old_name='diseace',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='ambulancemodel',
            old_name='patientage',
            new_name='patient_age',
        ),
        migrations.RenameField(
            model_name='ambulancemodel',
            old_name='patientname',
            new_name='patient_name',
        ),
    ]
