# Generated by Django 3.2.5 on 2021-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20210715_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('e', models.CharField(max_length=30)),
                ('f', models.CharField(max_length=30)),
                ('g', models.CharField(max_length=30)),
                ('h', models.CharField(max_length=30)),
            ],
        ),
    ]
