# Generated by Django 3.2.5 on 2021-07-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_appointmentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='b',
            new_name='appoinment_date',
        ),
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='c',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='d',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='e',
            new_name='if_before_visite_visit_detail',
        ),
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='f',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='g',
            new_name='previous_visit',
        ),
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='h',
            new_name='slot',
        ),
    ]
