# Generated by Django 3.2.5 on 2021-07-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_rename_if_before_visite_visit_detail_appointmentmodel_if_before_visited_visit_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='appoinment_date',
            new_name='appointment_date',
        ),
    ]
