# Generated by Django 3.2.5 on 2021-07-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_rename_appoinment_date_appointmentmodel_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
