# Generated by Django 3.2.5 on 2021-07-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drformmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(choices=[('BHMS', 'BHMS'), ('BAMS', 'BAMS'), ('MBBS', 'MBBS'), ('Physiotherapists', 'Physiotherapists'), ('MD', 'MD')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='newapp/images'),
        ),
    ]
