# Generated by Django 3.2.5 on 2021-07-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_auto_20210722_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nursingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('famale', 'female')], max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(choices=[('BSC Nursing', 'BSC Nursing'), ('Graduation+Nursing Cource', 'Graduation+Nursing Cource')], max_length=30)),
            ],
        ),
    ]
