# Generated by Django 3.2.5 on 2021-07-26 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0017_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Ordersmodel',
        ),
    ]
