# Generated by Django 3.2.5 on 2021-07-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_auto_20210726_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='statuc',
            field=models.BooleanField(default=False),
        ),
    ]
